import type { Artigo } from "./tipos";

/**
 * Biblioteca editorial do QAP, QRV!
 * Cada artigo tem ~600-900 palavras, TOC explícito e FAQ opcional.
 * Adicionar novos artigos aqui não requer mudança de código de rota.
 */
export const ARTIGOS: Artigo[] = [
  {
    slug: "guia-dejem-completo",
    title: "Guia completo da DEJEM: como funciona na PMESP",
    subtitle: "Regras, inscrição, remuneração e cuidados práticos para o Detalhe de Jornada Extra Militar",
    category: "dejem",
    date: "2026-05-02",
    readingMinutes: 8,
    author: "Equipe QAP, QRV!",
    toc: ["O que é a DEJEM", "Quem pode participar", "Como se inscrever", "Como a escala é montada", "Remuneração", "Cuidados práticos", "Erros comuns"],
    body: [
      "A Dejem — Detalhe de Jornada Extra Militar — é uma das principais formas de jornada complementar remunerada disponíveis ao policial militar do Estado de São Paulo. Ela permite reforçar o policiamento em pontos e horários definidos pela Corporação, com remuneração por hora trabalhada, fora do horário de serviço ordinário.",
      { h: "O que é a DEJEM" },
      "Regulamentada por diretriz específica da PMESP, a Dejem é facultativa: o militar só entra se se inscrever e for convocado. Cada OPM publica as necessidades do período — rádio-patrulha, policiamento a pé, motopatrulhamento, atendimento ao público e reforços definidos pelo comando local — e organiza a distribuição respeitando os intervalos mínimos de descanso.",
      { h: "Quem pode participar" },
      "Podem participar policiais militares da ativa que estejam em condições de saúde compatíveis com a jornada extra, sem impedimentos disciplinares e que atendam aos requisitos da diretriz vigente. Alunos e casos específicos seguem regras próprias.",
      { h: "Como se inscrever" },
      "A inscrição é feita pela intranet PMESP, dentro do sistema de escalas. O QAP, QRV! oferece atalho direto para essa página na Home: basta tocar em 'Marcar / Desmarcar Dejem/Delegada'. É necessário estar com a VPN AnyConnect ativa se estiver fora da rede corporativa.",
      { h: "Como a escala é montada" },
      "A OPM consolida as inscrições, prioriza a antiguidade e a disponibilidade e publica a escala oficial em PDF. Cada policial recebe seu ID de escala e pode consultar o documento pela consulta de escala do QAP, QRV! ou pela intranet.",
      { h: "Remuneração" },
      "A Dejem é paga pelo Governo do Estado por hora trabalhada, com valores definidos por tabela vigente. O crédito aparece em rubrica separada no contracheque, com incidência de tributos na fonte conforme legislação.",
      { h: "Cuidados práticos" },
      {
        list: [
          "Confira sempre local, horário e função antes de sair de casa.",
          "Respeite o intervalo mínimo entre a Dejem e o serviço ordinário.",
          "Leve todo o material orgânico em ordem: colete, arma, munição, rádio, TIM.",
          "Em caso de impedimento, comunique a chefia com antecedência.",
          "Baixe o PDF da escala para consulta offline.",
        ],
      },
      { h: "Erros comuns" },
      "Os erros mais comuns são: inscrever-se sem verificar disponibilidade real, esquecer o intervalo mínimo entre serviços e chegar sem conferir a função no dia. Todos evitáveis com uma agenda organizada e conferência prévia. Use o calendário do QAP, QRV! para não ter surpresas.",
    ],
    faq: [
      { q: "Posso fazer Dejem no dia seguinte ao serviço ordinário?", a: "Depende do intervalo previsto na diretriz vigente. Consulte sua Seção de Pessoal antes de se inscrever." },
      { q: "A Dejem entra no cálculo da aposentadoria?", a: "Não. É jornada complementar remunerada e não integra o soldo para fins previdenciários." },
    ],
    related: ["diferenca-dejem-delegada-2026", "planejamento-plantao"],
  },
  {
    slug: "diferenca-dejem-delegada-2026",
    title: "DEJEM x Operação Delegada: o comparativo definitivo",
    subtitle: "Quem paga, onde se atua e o que muda no contracheque",
    category: "delegada",
    date: "2026-05-05",
    readingMinutes: 6,
    author: "Equipe QAP, QRV!",
    toc: ["Origem de cada operação", "Quem paga", "Onde se atua", "Inscrição", "Remuneração", "Qual escolher"],
    body: [
      "Muito policial ainda confunde Dejem e Operação Delegada porque ambas são jornadas extras remuneradas. Mas elas nascem de fontes diferentes e obedecem regras próprias. Entender essa diferença ajuda a planejar a agenda com segurança.",
      { h: "Origem de cada operação" },
      "A Dejem é uma jornada extra da própria PMESP, custeada pelo Governo do Estado. A Operação Delegada nasce de convênios entre a Corporação e prefeituras (São Paulo é o exemplo mais conhecido, mas outros municípios também aderiram).",
      { h: "Quem paga" },
      "Na Dejem, a fonte pagadora é o Estado de São Paulo. Na Delegada, é a prefeitura que firmou o convênio. Isso impacta valores, prazos de pagamento e rubricas no contracheque.",
      { h: "Onde se atua" },
      "A Dejem cobre pontos definidos pela unidade — reforço em áreas críticas, complemento de policiamento ostensivo. A Delegada é pautada por demandas municipais: feiras, terminais, áreas comerciais, eventos e zeladoria urbana.",
      { h: "Inscrição" },
      "As duas usam a intranet PMESP, mas em sistemas próprios com editais separados. Confira o edital de cada operação para vagas, requisitos e valores.",
      { h: "Remuneração" },
      "Os valores por hora são diferentes e podem variar entre operações. Nos dois casos, o valor aparece em rubrica específica do contracheque e tem tributação na fonte.",
      { h: "Qual escolher" },
      "Não há resposta única. Muitos policiais combinam as duas conforme disponibilidade e proximidade do local. Use o Calendário do QAP, QRV! para ver ambas na mesma agenda e evitar conflitos.",
    ],
    faq: [
      { q: "Posso fazer Dejem e Delegada no mesmo dia?", a: "Somente se respeitados os intervalos mínimos e desde que não haja sobreposição de horário." },
    ],
    related: ["guia-dejem-completo", "planejamento-plantao"],
  },
  {
    slug: "planejamento-plantao",
    title: "Como organizar sua escala de plantão sem se desgastar",
    subtitle: "Sono, alimentação, revezamento e ferramentas digitais",
    category: "escalas",
    date: "2026-05-08",
    readingMinutes: 7,
    author: "Equipe QAP, QRV!",
    toc: ["Escolha um modelo de escala", "Priorize o sono", "Alimentação inteligente", "Use o calendário", "Comunique-se com a família", "Evite acúmulo excessivo"],
    body: [
      "Trabalhar em regime de plantão exige mais do que disposição: exige planejamento. O corpo e a mente pagam preço alto quando a escala vira improviso. Este guia reúne práticas simples que fazem grande diferença no longo prazo.",
      { h: "Escolha um modelo de escala" },
      "Modelos como 12x24, 12x48 e 24x72 são comuns na PMESP. Cada um tem prós e contras. O 12x48 tende a preservar melhor o descanso; o 12x24 aumenta a frequência de serviço. Discuta com sua chefia o modelo que sua unidade adota e o impacto no seu ritmo.",
      { h: "Priorize o sono" },
      "Sono fragmentado é a principal causa de fadiga crônica. Estabeleça janelas fixas de sono, mesmo em folgas curtas. Use blackout, ruído branco e evite telas 30 minutos antes de dormir.",
      { h: "Alimentação inteligente" },
      "Refeições leves antes do serviço, hidratação constante e evitar excesso de cafeína após o meio do turno mantêm a atenção sem provocar picos de energia seguidos de queda.",
      { h: "Use o calendário" },
      "Marque cada plantão no Calendário do QAP, QRV! e ative lembretes 60 e 120 minutos antes. Ver a semana inteira de uma vez evita compromissos conflitantes.",
      { h: "Comunique-se com a família" },
      "Compartilhe a escala com quem convive com você. O app permite exportar em .ics para o Google Agenda familiar.",
      { h: "Evite acúmulo excessivo" },
      "Somar Dejem, Delegada e escala ordinária sem intervalo é receita para acidente e afastamento. Respeite os intervalos mínimos.",
    ],
    related: ["guia-dejem-completo", "escala-12x24-x-12x48"],
  },
  {
    slug: "escala-12x24-x-12x48",
    title: "Escala 12x24 ou 12x48: qual é melhor para o policial?",
    subtitle: "Análise prática dos dois modelos mais usados",
    category: "escalas",
    date: "2026-05-11",
    readingMinutes: 6,
    author: "Equipe QAP, QRV!",
    toc: ["Como cada escala funciona", "Impacto no descanso", "Impacto na renda", "Qualidade de vida", "Como decidir"],
    body: [
      "A escolha entre 12x24 e 12x48 (ou 24x72) é uma das discussões mais frequentes entre policiais em regime de plantão. Cada modelo tem trade-offs claros.",
      { h: "Como cada escala funciona" },
      "Na 12x24, o policial trabalha 12 horas e folga 24. Na 12x48, trabalha 12 horas e folga 48. A 12x24 gera mais serviços por mês; a 12x48, menos.",
      { h: "Impacto no descanso" },
      "12x48 oferece dois dias completos de folga, permitindo recuperação real do sono e da rotina familiar. Já a 12x24 encurta o ciclo e favorece fadiga acumulada, especialmente em serviço noturno.",
      { h: "Impacto na renda" },
      "Se a base salarial é por soldo, ambas rendem o mesmo. Se há complementos por hora, a 12x24 rende mais no curto prazo, mas com maior desgaste.",
      { h: "Qualidade de vida" },
      "12x48 é mais amiga da família e dos estudos. 12x24 é usada em unidades com déficit de efetivo e demanda operacional intensa.",
      { h: "Como decidir" },
      "Nem sempre há escolha: depende da unidade. Quando houver, prefira 12x48 se puder — o ganho em saúde e presença familiar compensa. Registre no Calendário do QAP, QRV! qualquer que seja o modelo para não perder plantão.",
    ],
    related: ["planejamento-plantao"],
  },
  {
    slug: "boas-praticas-intranet-pmesp",
    title: "Boas práticas ao usar a intranet PMESP",
    subtitle: "Segurança, VPN, senhas e economia de tempo",
    category: "procedimentos",
    date: "2026-05-14",
    readingMinutes: 5,
    author: "Equipe QAP, QRV!",
    toc: ["Sempre com VPN", "Cuidado com senhas", "Evite salvar em navegador público", "Feche a sessão", "Reporte problemas"],
    body: [
      "A intranet da PMESP é ferramenta central para escala, contracheque, ofícios e comunicações. Alguns hábitos simples evitam dor de cabeça.",
      { h: "Sempre com VPN" },
      "Fora da rede corporativa, acesse sempre com AnyConnect ativa. O QAP, QRV! detecta e avisa se a VPN está desligada.",
      { h: "Cuidado com senhas" },
      "Não reutilize a senha da intranet em serviços pessoais. Troque com frequência e use gerenciador seguro.",
      { h: "Evite salvar em navegador público" },
      "Nunca salve senhas em computador de lan house, biblioteca ou aparelho emprestado.",
      { h: "Feche a sessão" },
      "Ao terminar, faça logout. Fechar apenas a aba pode deixar a sessão ativa.",
      { h: "Reporte problemas" },
      "Instabilidade ou erro estranho? Reporte à sua unidade e ao suporte oficial. O QAP, QRV! não substitui a intranet — apenas facilita atalhos.",
    ],
    related: ["seguranca-anyconnect", "senha-forte-policial"],
  },
  {
    slug: "seguranca-anyconnect",
    title: "Cisco AnyConnect na PMESP: instalação, uso e problemas comuns",
    subtitle: "O que é a VPN AnyConnect, como configurar e como resolver erros",
    category: "seguranca-digital",
    date: "2026-05-17",
    readingMinutes: 7,
    author: "Equipe QAP, QRV!",
    toc: ["O que é a VPN AnyConnect", "Por que a PMESP usa", "Instalação no Android", "Instalação no Windows", "Problemas comuns", "Boas práticas"],
    body: [
      "A VPN AnyConnect da Cisco é a ferramenta que permite ao policial militar acessar sistemas internos da PMESP a partir de redes externas com segurança.",
      { h: "O que é a VPN AnyConnect" },
      "É uma VPN corporativa que cifra o tráfego entre o dispositivo do usuário e a rede da instituição, evitando interceptação em Wi-Fi público.",
      { h: "Por que a PMESP usa" },
      "Sistemas como escala, folha de pagamento e intranet são disponibilizados apenas para IPs autorizados. A VPN é o passe de entrada.",
      { h: "Instalação no Android" },
      "Baixe o app 'Cisco Secure Client' pela Play Store, configure o servidor conforme orientação da sua unidade e faça login com suas credenciais corporativas.",
      { h: "Instalação no Windows" },
      "O instalador oficial fica disponível na intranet. Após instalar, informe o endereço do gateway VPN e as credenciais.",
      { h: "Problemas comuns" },
      {
        list: [
          "Login inválido: confirme se está usando a senha da intranet.",
          "Servidor não encontrado: verifique conexão Wi-Fi/4G.",
          "Certificado inválido: normalmente pede aceitar a exceção.",
          "Desconexão constante: pode ser instabilidade da rede local.",
        ],
      },
      { h: "Boas práticas" },
      "Desligue a VPN quando não estiver usando serviços internos para preservar bateria. Nunca compartilhe suas credenciais. Consulte o vídeo tutorial ANYCONECT no menu do QAP, QRV!.",
    ],
    related: ["boas-praticas-intranet-pmesp", "senha-forte-policial"],
  },
  {
    slug: "senha-forte-policial",
    title: "Senha forte para o policial: como criar e proteger",
    subtitle: "Regras práticas para senhas de intranet, e-mail e serviços críticos",
    category: "seguranca-digital",
    date: "2026-05-19",
    readingMinutes: 5,
    author: "Equipe QAP, QRV!",
    toc: ["O que é senha forte", "Erros a evitar", "Gerenciador de senhas", "Autenticação em duas etapas", "O que fazer se vazou"],
    body: [
      "Senha fraca é porta aberta. Para quem lida com sistemas sensíveis, o cuidado precisa ser dobrado.",
      { h: "O que é senha forte" },
      "Mínimo de 12 caracteres, misturando maiúsculas, minúsculas, números e símbolos, sem palavras óbvias. Frases-senha (ex.: 'CafédeSegunda!7Amarelo') são fáceis de lembrar e difíceis de quebrar.",
      { h: "Erros a evitar" },
      "Não use data de nascimento, matrícula, nome de filho ou nome da unidade. Não reutilize senha entre sistemas críticos e pessoais.",
      { h: "Gerenciador de senhas" },
      "Aplicativos como Bitwarden, 1Password ou o gerenciador do próprio navegador ajudam a criar e guardar senhas únicas por serviço.",
      { h: "Autenticação em duas etapas" },
      "Sempre que possível, ative o 2FA. É a barreira mais eficaz contra invasão por senha vazada.",
      { h: "O que fazer se vazou" },
      "Troque imediatamente em todos os serviços onde usava a mesma senha e ative 2FA. Reporte à sua unidade se envolver sistema corporativo.",
    ],
    related: ["seguranca-anyconnect"],
  },
  {
    slug: "calendario-operacional-guia",
    title: "Como usar o calendário operacional do QAP, QRV!",
    subtitle: "Passo a passo: plantões, avulsos, compromissos e exportação",
    category: "ferramentas",
    date: "2026-05-22",
    readingMinutes: 6,
    author: "Equipe QAP, QRV!",
    toc: ["Visão geral", "Adicionar plantão recorrente", "Adicionar plantão avulso", "Adicionar compromisso", "Cores automáticas", "Exportar para o Google Agenda"],
    body: [
      "O Calendário é o coração do QAP, QRV!. Ele centraliza escalas, compromissos e horas trabalhadas.",
      { h: "Visão geral" },
      "Cada célula do calendário representa um dia. Um plantão de dia (06h–18h) recebe fundo dourado; noite (18h–06h), azul-marinho. Compromissos pessoais aparecem como post-it amarelo. Um risco horizontal azul marca o dia de hoje.",
      { h: "Adicionar plantão recorrente" },
      "Use 'Configurar escala' para plantões que se repetem em ciclo (12x24, 12x48, 24x72). Basta escolher a data de início, o modelo e o horário.",
      { h: "Adicionar plantão avulso" },
      "Toque no dia e escolha 'Adicionar plantão'. Ideal para Dejem ou Delegada específicos.",
      { h: "Adicionar compromisso" },
      "Toque no dia e escolha 'Adicionar compromisso'. Útil para reuniões, formaturas, cursos.",
      { h: "Cores automáticas" },
      "As cores dia/noite são fixas para você bater o olho e saber. Sem risco de confundir com outros usuários.",
      { h: "Exportar para o Google Agenda" },
      "Use a opção de exportar .ics no topo do calendário. Importe o arquivo no Google Agenda, Apple Calendário ou Outlook.",
    ],
    related: ["planejamento-plantao"],
  },
  {
    slug: "backup-e-privacidade-app",
    title: "Backup e privacidade no QAP, QRV!",
    subtitle: "Onde ficam seus dados e como protegê-los",
    category: "tecnologia",
    date: "2026-05-25",
    readingMinutes: 5,
    author: "Equipe QAP, QRV!",
    toc: ["Onde os dados ficam", "Backup manual", "Backup no APK", "Restauração", "Privacidade"],
    body: [
      "O QAP, QRV! foi desenhado com privacidade em primeiro lugar. Nada dos seus dados operacionais é enviado a servidor.",
      { h: "Onde os dados ficam" },
      "Plantões, marcas, preferências e escalas salvas ficam no armazenamento local do navegador (IndexedDB/localStorage) ou no armazenamento do APK Android.",
      { h: "Backup manual" },
      "Em Configurações → 'Exportar dados', gere um JSON e salve na nuvem pessoal (Drive, iCloud).",
      { h: "Backup no APK" },
      "O APK também permite exportar o mesmo JSON. É recomendável fazer backup mensal.",
      { h: "Restauração" },
      "Ao reinstalar, use 'Importar dados' e selecione o JSON exportado. Os dados voltam intactos.",
      { h: "Privacidade" },
      "O app não coleta senha, contracheque ou informação sensível. Anúncios (quando exibidos) rodam apenas em páginas editoriais públicas e nunca dentro das ferramentas.",
    ],
    related: ["calendario-operacional-guia"],
  },
  {
    slug: "produtividade-policial",
    title: "Produtividade para policiais em regime de escala",
    subtitle: "Hábitos, aplicativos e disciplina para render mais sem se esgotar",
    category: "produtividade",
    date: "2026-05-28",
    readingMinutes: 6,
    author: "Equipe QAP, QRV!",
    toc: ["Comece pelo sono", "Bloqueie tempo", "Reduza notificações", "Estude em blocos", "Automatize o que puder"],
    body: [
      "Produtividade não é fazer mais em menos tempo — é proteger o essencial. Para o policial em escala, isso significa cuidar do corpo, do estudo e da família.",
      { h: "Comece pelo sono" },
      "Sem sono, produtividade despenca. Duas noites mal dormidas comprometem duas semanas.",
      { h: "Bloqueie tempo" },
      "Reserve blocos fixos para estudo, exercício e família. Compromisso com você mesmo também vai no calendário.",
      { h: "Reduza notificações" },
      "Desative badges de redes sociais. Deixe ativas apenas as do QAP, QRV! e apps essenciais.",
      { h: "Estude em blocos" },
      "Sessões de 45 minutos com 10 de pausa (técnica Pomodoro adaptada) rendem mais que 3 horas seguidas.",
      { h: "Automatize o que puder" },
      "Ferramentas como calendário, lembretes automáticos e backup poupam energia mental. Deixe o app trabalhar.",
    ],
    related: ["planejamento-plantao"],
  },
  {
    slug: "pmesp-canais-oficiais",
    title: "PMESP: canais oficiais e onde buscar informação confiável",
    subtitle: "Sites, apps e telefones da Polícia Militar do Estado de São Paulo",
    category: "pmesp",
    date: "2026-05-31",
    readingMinutes: 4,
    author: "Equipe QAP, QRV!",
    toc: ["Portais oficiais", "Ouvidoria", "Ensino", "Redes sociais"],
    body: [
      "O QAP, QRV! é ferramenta auxiliar. Para informação oficial, sempre consulte a fonte primária.",
      { h: "Portais oficiais" },
      "O portal principal da PMESP concentra editais, comunicados e diretrizes. A intranet acessa serviços internos como escala e folha.",
      { h: "Ouvidoria" },
      "A Ouvidoria da PMESP é o canal para elogios, sugestões e denúncias. As informações são tratadas com sigilo.",
      { h: "Ensino" },
      "O PVT (Portal Virtual do Ensino) concentra cursos, especializações e material didático da Corporação.",
      { h: "Redes sociais" },
      "Perfis oficiais da PMESP no Instagram e no X publicam ações e alertas em tempo real. Sempre confira se é a conta verificada.",
    ],
    related: [],
  },
  {
    slug: "instalar-pwa-android",
    title: "Como instalar o QAP, QRV! como app no Android",
    subtitle: "Passo a passo pelo Chrome e sem precisar da Play Store",
    category: "tecnologia",
    date: "2026-06-03",
    readingMinutes: 4,
    author: "Equipe QAP, QRV!",
    toc: ["Pelo Chrome", "Pelo APK", "Benefícios", "Desinstalação"],
    body: [
      "O QAP, QRV! é um PWA — instala como app sem passar pela Play Store, e ainda existe APK oficial.",
      { h: "Pelo Chrome" },
      "Abra o site no Chrome, toque no menu ⋮ e selecione 'Instalar app' ou 'Adicionar à tela inicial'. O ícone aparece na home do celular e abre em tela cheia.",
      { h: "Pelo APK" },
      "Se preferir, baixe o APK oficial na seção de download. Habilite a instalação de fontes desconhecidas se solicitado.",
      { h: "Benefícios" },
      "App instalado abre mais rápido, funciona offline, envia notificações e ocupa muito menos espaço que apps convencionais.",
      { h: "Desinstalação" },
      "Segure o ícone → Desinstalar. Seus dados locais podem ser exportados antes.",
    ],
    related: ["backup-e-privacidade-app"],
  },
];

export function getArtigo(slug: string) {
  return ARTIGOS.find((a) => a.slug === slug);
}

export function artigosPorCategoria(cat: string) {
  return ARTIGOS.filter((a) => a.category === cat);
}
