/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MapaDoSiteRouteImport } from './routes/mapa-do-site'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as IntranetRouteImport } from './routes/intranet'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as Googlef2edc9e3a6b2e4a9DothtmlRouteImport } from './routes/googlef2edc9e3a6b2e4a9[.]html'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EscalasBaixadasRouteImport } from './routes/escalas-baixadas'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AvisoLegalRouteImport } from './routes/aviso-legal'
import { Route as AnyconnectRouteImport } from './routes/anyconnect'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as FerramentaMinhaLocalizacaoRouteImport } from './routes/ferramenta.minha-localizacao'
import { Route as FerramentaConsultaEscalaRouteImport } from './routes/ferramenta.consulta-escala'
import { Route as FerramentaSlugRouteImport } from './routes/ferramenta.$slug'
import { Route as EscalaViewerIdRouteImport } from './routes/escala-viewer.$id'
import { Route as ConteudosCategoriaRouteImport } from './routes/conteudos.$categoria'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ConteudosCategoriaSlugRouteImport } from './routes/conteudos.$categoria.$slug'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaDoSiteRoute = MapaDoSiteRouteImport.update({
  id: '/mapa-do-site',
  path: '/mapa-do-site',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetRoute = IntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const Googlef2edc9e3a6b2e4a9DothtmlRoute =
  Googlef2edc9e3a6b2e4a9DothtmlRouteImport.update({
    id: '/googlef2edc9e3a6b2e4a9.html',
    path: '/googlef2edc9e3a6b2e4a9.html',
    getParentRoute: () => rootRouteImport,
  } as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasBaixadasRoute = EscalasBaixadasRouteImport.update({
  id: '/escalas-baixadas',
  path: '/escalas-baixadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AvisoLegalRoute = AvisoLegalRouteImport.update({
  id: '/aviso-legal',
  path: '/aviso-legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnyconnectRoute = AnyconnectRouteImport.update({
  id: '/anyconnect',
  path: '/anyconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentaMinhaLocalizacaoRoute =
  FerramentaMinhaLocalizacaoRouteImport.update({
    id: '/ferramenta/minha-localizacao',
    path: '/ferramenta/minha-localizacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const FerramentaConsultaEscalaRoute =
  FerramentaConsultaEscalaRouteImport.update({
    id: '/ferramenta/consulta-escala',
    path: '/ferramenta/consulta-escala',
    getParentRoute: () => rootRouteImport,
  } as any)
const FerramentaSlugRoute = FerramentaSlugRouteImport.update({
  id: '/ferramenta/$slug',
  path: '/ferramenta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalaViewerIdRoute = EscalaViewerIdRouteImport.update({
  id: '/escala-viewer/$id',
  path: '/escala-viewer/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosCategoriaRoute = ConteudosCategoriaRouteImport.update({
  id: '/$categoria',
  path: '/$categoria',
  getParentRoute: () => ConteudosRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const ConteudosCategoriaSlugRoute = ConteudosCategoriaSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ConteudosCategoriaRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/anyconnect': typeof AnyconnectRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/googlef2edc9e3a6b2e4a9.html': typeof Googlef2edc9e3a6b2e4a9DothtmlRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$categoria': typeof ConteudosCategoriaRouteWithChildren
  '/escala-viewer/$id': typeof EscalaViewerIdRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/conteudos/$categoria/$slug': typeof ConteudosCategoriaSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/anyconnect': typeof AnyconnectRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/googlef2edc9e3a6b2e4a9.html': typeof Googlef2edc9e3a6b2e4a9DothtmlRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$categoria': typeof ConteudosCategoriaRouteWithChildren
  '/escala-viewer/$id': typeof EscalaViewerIdRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/conteudos/$categoria/$slug': typeof ConteudosCategoriaSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/anyconnect': typeof AnyconnectRoute
  '/aviso-legal': typeof AvisoLegalRoute
  '/blog': typeof BlogRouteWithChildren
  '/calendario': typeof CalendarioRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contato': typeof ContatoRoute
  '/cookies': typeof CookiesRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/faq': typeof FaqRoute
  '/favoritos': typeof FavoritosRoute
  '/googlef2edc9e3a6b2e4a9.html': typeof Googlef2edc9e3a6b2e4a9DothtmlRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/mapa-do-site': typeof MapaDoSiteRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/termos': typeof TermosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/conteudos/$categoria': typeof ConteudosCategoriaRouteWithChildren
  '/escala-viewer/$id': typeof EscalaViewerIdRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/conteudos/$categoria/$slug': typeof ConteudosCategoriaSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/anyconnect'
    | '/aviso-legal'
    | '/blog'
    | '/calendario'
    | '/configuracoes'
    | '/contato'
    | '/cookies'
    | '/escalas-baixadas'
    | '/faq'
    | '/favoritos'
    | '/googlef2edc9e3a6b2e4a9.html'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/mapa-do-site'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/termos'
    | '/blog/$slug'
    | '/conteudos/$categoria'
    | '/escala-viewer/$id'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
    | '/conteudos/'
    | '/conteudos/$categoria/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/anyconnect'
    | '/aviso-legal'
    | '/blog'
    | '/calendario'
    | '/configuracoes'
    | '/contato'
    | '/cookies'
    | '/escalas-baixadas'
    | '/faq'
    | '/favoritos'
    | '/googlef2edc9e3a6b2e4a9.html'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/mapa-do-site'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/termos'
    | '/blog/$slug'
    | '/conteudos/$categoria'
    | '/escala-viewer/$id'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
    | '/conteudos'
    | '/conteudos/$categoria/$slug'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/anyconnect'
    | '/aviso-legal'
    | '/blog'
    | '/calendario'
    | '/configuracoes'
    | '/contato'
    | '/cookies'
    | '/escalas-baixadas'
    | '/faq'
    | '/favoritos'
    | '/googlef2edc9e3a6b2e4a9.html'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/mapa-do-site'
    | '/onboarding'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/termos'
    | '/blog/$slug'
    | '/conteudos/$categoria'
    | '/escala-viewer/$id'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
    | '/conteudos/'
    | '/conteudos/$categoria/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  AnyconnectRoute: typeof AnyconnectRoute
  AvisoLegalRoute: typeof AvisoLegalRoute
  BlogRoute: typeof BlogRouteWithChildren
  CalendarioRoute: typeof CalendarioRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContatoRoute: typeof ContatoRoute
  CookiesRoute: typeof CookiesRoute
  EscalasBaixadasRoute: typeof EscalasBaixadasRoute
  FaqRoute: typeof FaqRoute
  FavoritosRoute: typeof FavoritosRoute
  Googlef2edc9e3a6b2e4a9DothtmlRoute: typeof Googlef2edc9e3a6b2e4a9DothtmlRoute
  HistoricoRoute: typeof HistoricoRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  InicioRoute: typeof InicioRoute
  IntranetRoute: typeof IntranetRoute
  ManualRoute: typeof ManualRoute
  MapaDoSiteRoute: typeof MapaDoSiteRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SplashRoute: typeof SplashRoute
  TermosRoute: typeof TermosRoute
  EscalaViewerIdRoute: typeof EscalaViewerIdRoute
  FerramentaSlugRoute: typeof FerramentaSlugRoute
  FerramentaConsultaEscalaRoute: typeof FerramentaConsultaEscalaRoute
  FerramentaMinhaLocalizacaoRoute: typeof FerramentaMinhaLocalizacaoRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa-do-site': {
      id: '/mapa-do-site'
      path: '/mapa-do-site'
      fullPath: '/mapa-do-site'
      preLoaderRoute: typeof MapaDoSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/googlef2edc9e3a6b2e4a9.html': {
      id: '/googlef2edc9e3a6b2e4a9.html'
      path: '/googlef2edc9e3a6b2e4a9.html'
      fullPath: '/googlef2edc9e3a6b2e4a9.html'
      preLoaderRoute: typeof Googlef2edc9e3a6b2e4a9DothtmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas-baixadas': {
      id: '/escalas-baixadas'
      path: '/escalas-baixadas'
      fullPath: '/escalas-baixadas'
      preLoaderRoute: typeof EscalasBaixadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviso-legal': {
      id: '/aviso-legal'
      path: '/aviso-legal'
      fullPath: '/aviso-legal'
      preLoaderRoute: typeof AvisoLegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anyconnect': {
      id: '/anyconnect'
      path: '/anyconnect'
      fullPath: '/anyconnect'
      preLoaderRoute: typeof AnyconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/minha-localizacao': {
      id: '/ferramenta/minha-localizacao'
      path: '/ferramenta/minha-localizacao'
      fullPath: '/ferramenta/minha-localizacao'
      preLoaderRoute: typeof FerramentaMinhaLocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/consulta-escala': {
      id: '/ferramenta/consulta-escala'
      path: '/ferramenta/consulta-escala'
      fullPath: '/ferramenta/consulta-escala'
      preLoaderRoute: typeof FerramentaConsultaEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/$slug': {
      id: '/ferramenta/$slug'
      path: '/ferramenta/$slug'
      fullPath: '/ferramenta/$slug'
      preLoaderRoute: typeof FerramentaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escala-viewer/$id': {
      id: '/escala-viewer/$id'
      path: '/escala-viewer/$id'
      fullPath: '/escala-viewer/$id'
      preLoaderRoute: typeof EscalaViewerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$categoria': {
      id: '/conteudos/$categoria'
      path: '/$categoria'
      fullPath: '/conteudos/$categoria'
      preLoaderRoute: typeof ConteudosCategoriaRouteImport
      parentRoute: typeof ConteudosRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/conteudos/$categoria/$slug': {
      id: '/conteudos/$categoria/$slug'
      path: '/$slug'
      fullPath: '/conteudos/$categoria/$slug'
      preLoaderRoute: typeof ConteudosCategoriaSlugRouteImport
      parentRoute: typeof ConteudosCategoriaRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  AnyconnectRoute: AnyconnectRoute,
  AvisoLegalRoute: AvisoLegalRoute,
  BlogRoute: BlogRouteWithChildren,
  CalendarioRoute: CalendarioRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContatoRoute: ContatoRoute,
  CookiesRoute: CookiesRoute,
  EscalasBaixadasRoute: EscalasBaixadasRoute,
  FaqRoute: FaqRoute,
  FavoritosRoute: FavoritosRoute,
  Googlef2edc9e3a6b2e4a9DothtmlRoute: Googlef2edc9e3a6b2e4a9DothtmlRoute,
  HistoricoRoute: HistoricoRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  InicioRoute: InicioRoute,
  IntranetRoute: IntranetRoute,
  ManualRoute: ManualRoute,
  MapaDoSiteRoute: MapaDoSiteRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SplashRoute: SplashRoute,
  TermosRoute: TermosRoute,
  EscalaViewerIdRoute: EscalaViewerIdRoute,
  FerramentaSlugRoute: FerramentaSlugRoute,
  FerramentaConsultaEscalaRoute: FerramentaConsultaEscalaRoute,
  FerramentaMinhaLocalizacaoRoute: FerramentaMinhaLocalizacaoRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
