/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ManualRouteImport } from './routes/manual'
import { Route as IntranetRouteImport } from './routes/intranet'
import { Route as InicioRouteImport } from './routes/inicio'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as EscalasBaixadasRouteImport } from './routes/escalas-baixadas'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AnyconnectRouteImport } from './routes/anyconnect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FerramentaMinhaLocalizacaoRouteImport } from './routes/ferramenta.minha-localizacao'
import { Route as FerramentaConsultaEscalaRouteImport } from './routes/ferramenta.consulta-escala'
import { Route as FerramentaSlugRouteImport } from './routes/ferramenta.$slug'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ManualRoute = ManualRouteImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRouteImport,
} as any)
const IntranetRoute = IntranetRouteImport.update({
  id: '/intranet',
  path: '/intranet',
  getParentRoute: () => rootRouteImport,
} as any)
const InicioRoute = InicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalasBaixadasRoute = EscalasBaixadasRouteImport.update({
  id: '/escalas-baixadas',
  path: '/escalas-baixadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AnyconnectRoute = AnyconnectRouteImport.update({
  id: '/anyconnect',
  path: '/anyconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentaMinhaLocalizacaoRoute =
  FerramentaMinhaLocalizacaoRouteImport.update({
    id: '/ferramenta/minha-localizacao',
    path: '/ferramenta/minha-localizacao',
    getParentRoute: () => rootRouteImport,
  } as any)
const FerramentaConsultaEscalaRoute =
  FerramentaConsultaEscalaRouteImport.update({
    id: '/ferramenta/consulta-escala',
    path: '/ferramenta/consulta-escala',
    getParentRoute: () => rootRouteImport,
  } as any)
const FerramentaSlugRoute = FerramentaSlugRouteImport.update({
  id: '/ferramenta/$slug',
  path: '/ferramenta/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anyconnect': typeof AnyconnectRoute
  '/calendario': typeof CalendarioRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anyconnect': typeof AnyconnectRoute
  '/calendario': typeof CalendarioRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anyconnect': typeof AnyconnectRoute
  '/calendario': typeof CalendarioRoute
  '/escalas-baixadas': typeof EscalasBaixadasRoute
  '/favoritos': typeof FavoritosRoute
  '/historico': typeof HistoricoRoute
  '/index': typeof Char91indexChar93Route
  '/inicio': typeof InicioRoute
  '/intranet': typeof IntranetRoute
  '/manual': typeof ManualRoute
  '/privacidade': typeof PrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/splash': typeof SplashRoute
  '/ferramenta/$slug': typeof FerramentaSlugRoute
  '/ferramenta/consulta-escala': typeof FerramentaConsultaEscalaRoute
  '/ferramenta/minha-localizacao': typeof FerramentaMinhaLocalizacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anyconnect'
    | '/calendario'
    | '/escalas-baixadas'
    | '/favoritos'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anyconnect'
    | '/calendario'
    | '/escalas-baixadas'
    | '/favoritos'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
  id:
    | '__root__'
    | '/'
    | '/anyconnect'
    | '/calendario'
    | '/escalas-baixadas'
    | '/favoritos'
    | '/historico'
    | '/index'
    | '/inicio'
    | '/intranet'
    | '/manual'
    | '/privacidade'
    | '/sitemap.xml'
    | '/sobre'
    | '/splash'
    | '/ferramenta/$slug'
    | '/ferramenta/consulta-escala'
    | '/ferramenta/minha-localizacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnyconnectRoute: typeof AnyconnectRoute
  CalendarioRoute: typeof CalendarioRoute
  EscalasBaixadasRoute: typeof EscalasBaixadasRoute
  FavoritosRoute: typeof FavoritosRoute
  HistoricoRoute: typeof HistoricoRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  InicioRoute: typeof InicioRoute
  IntranetRoute: typeof IntranetRoute
  ManualRoute: typeof ManualRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SplashRoute: typeof SplashRoute
  FerramentaSlugRoute: typeof FerramentaSlugRoute
  FerramentaConsultaEscalaRoute: typeof FerramentaConsultaEscalaRoute
  FerramentaMinhaLocalizacaoRoute: typeof FerramentaMinhaLocalizacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intranet': {
      id: '/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof IntranetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inicio': {
      id: '/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof InicioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalas-baixadas': {
      id: '/escalas-baixadas'
      path: '/escalas-baixadas'
      fullPath: '/escalas-baixadas'
      preLoaderRoute: typeof EscalasBaixadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anyconnect': {
      id: '/anyconnect'
      path: '/anyconnect'
      fullPath: '/anyconnect'
      preLoaderRoute: typeof AnyconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/minha-localizacao': {
      id: '/ferramenta/minha-localizacao'
      path: '/ferramenta/minha-localizacao'
      fullPath: '/ferramenta/minha-localizacao'
      preLoaderRoute: typeof FerramentaMinhaLocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/consulta-escala': {
      id: '/ferramenta/consulta-escala'
      path: '/ferramenta/consulta-escala'
      fullPath: '/ferramenta/consulta-escala'
      preLoaderRoute: typeof FerramentaConsultaEscalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramenta/$slug': {
      id: '/ferramenta/$slug'
      path: '/ferramenta/$slug'
      fullPath: '/ferramenta/$slug'
      preLoaderRoute: typeof FerramentaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnyconnectRoute: AnyconnectRoute,
  CalendarioRoute: CalendarioRoute,
  EscalasBaixadasRoute: EscalasBaixadasRoute,
  FavoritosRoute: FavoritosRoute,
  HistoricoRoute: HistoricoRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  InicioRoute: InicioRoute,
  IntranetRoute: IntranetRoute,
  ManualRoute: ManualRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SplashRoute: SplashRoute,
  FerramentaSlugRoute: FerramentaSlugRoute,
  FerramentaConsultaEscalaRoute: FerramentaConsultaEscalaRoute,
  FerramentaMinhaLocalizacaoRoute: FerramentaMinhaLocalizacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
